apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/kubernetes-id: client-hub
  name: my-client-hub-test
spec:
  lifecycle: production
  owner: my-team
  type: service
